/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cecs543;

import static cecs543.Language.chkBoxAda;
import static cecs543.Language.chkBoxAssembler;
import static cecs543.Language.chkBoxC;
import static cecs543.Language.chkBoxCPP;
import static cecs543.Language.chkBoxCS;
import static cecs543.Language.chkBoxCobol;
import static cecs543.Language.chkBoxFortran;
import static cecs543.Language.chkBoxHtml;
import static cecs543.Language.chkBoxJava;
import static cecs543.Language.chkBoxJavaScript;
import static cecs543.Language.chkBoxVBScript;
import static cecs543.Language.chkBoxVisualBasic;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Ankush
 */
public class ChangeLanguage extends javax.swing.JFrame {

    /**
     * Creates new form Language
     */
    public FP fp;
    
    
    public ChangeLanguage(FP fp) {
        initComponents();
        this.fp = fp;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkBoxGrp = new javax.swing.ButtonGroup();
        chkBoxAssembler = new javax.swing.JCheckBox();
        chkBoxAda = new javax.swing.JCheckBox();
        chkBoxC = new javax.swing.JCheckBox();
        chkBoxCPP = new javax.swing.JCheckBox();
        chkBoxCS = new javax.swing.JCheckBox();
        chkBoxCobol = new javax.swing.JCheckBox();
        chkBoxFortran = new javax.swing.JCheckBox();
        chkBoxHtml = new javax.swing.JCheckBox();
        chkBoxJava = new javax.swing.JCheckBox();
        chkBoxJavaScript = new javax.swing.JCheckBox();
        chkBoxVBScript = new javax.swing.JCheckBox();
        chkBoxVisualBasic = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btnDone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        chkBoxGrp.add(chkBoxAssembler);
        chkBoxAssembler.setText("Assembler");

        chkBoxGrp.add(chkBoxAda);
        chkBoxAda.setText("Ada 95");

        chkBoxGrp.add(chkBoxC);
        chkBoxC.setText("C");

        chkBoxGrp.add(chkBoxCPP);
        chkBoxCPP.setText("C++");

        chkBoxGrp.add(chkBoxCS);
        chkBoxCS.setText("C#");

        chkBoxGrp.add(chkBoxCobol);
        chkBoxCobol.setText("COBOL");

        chkBoxGrp.add(chkBoxFortran);
        chkBoxFortran.setText("FORTRAN");

        chkBoxGrp.add(chkBoxHtml);
        chkBoxHtml.setText("HTML");

        chkBoxGrp.add(chkBoxJava);
        chkBoxJava.setText("Java");

        chkBoxGrp.add(chkBoxJavaScript);
        chkBoxJavaScript.setText("JavaScript");

        chkBoxGrp.add(chkBoxVBScript);
        chkBoxVBScript.setText("VBScript");

        chkBoxGrp.add(chkBoxVisualBasic);
        chkBoxVisualBasic.setText("Visual Basic");

        jLabel1.setText("Select One Language");

        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDone)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chkBoxAda)
                                .addComponent(chkBoxAssembler)
                                .addComponent(chkBoxC)
                                .addComponent(chkBoxCPP)
                                .addComponent(chkBoxCS)
                                .addComponent(chkBoxCobol)
                                .addComponent(chkBoxFortran)
                                .addComponent(chkBoxJavaScript)
                                .addComponent(chkBoxJava)
                                .addComponent(chkBoxHtml)
                                .addComponent(chkBoxVBScript)
                                .addComponent(chkBoxVisualBasic)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(chkBoxAssembler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBoxAda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBoxC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBoxCPP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBoxCS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBoxCobol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBoxFortran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBoxHtml)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBoxJava)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBoxJavaScript)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBoxVBScript)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBoxVisualBasic)
                .addGap(18, 18, 18)
                .addComponent(btnDone)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        // TODO add your handling code here:
        FP.LangYaMenu = 0;
        int count = 0;
        int selectedIndex = fp.TabbedPanel.getSelectedIndex();
        //System.out.println(selectedIndex);
        calculation c = (calculation) fp.TabbedPanel.getComponentAt(selectedIndex);
        
        //System.out.println(selectedIndex);
        if(chkBoxAda.isSelected())
        {
            //FP.TabbedPanel.addTab("tabAda",c );
            FP.cal.put(1,c);
            FP.i[1] = 1;
            FP.visited[1] = 1;
            c.txtLang.setText("Ada");
            count = count + 1;
           
        }
        if(chkBoxAssembler.isSelected())
        {
            //FP.TabbedPanel.addTab("tabAssembler",c );
            FP.cal.put(0,c);
            FP.i[0] = 0;
            c.txtLang.setText("Assembler");
            FP.visited[0] = 0;
            count = count + 1;
        }
        if(chkBoxC.isSelected())
        {
            //FP.TabbedPanel.addTab("tabC",c );
            FP.cal.put(2,c);
            FP.i[2] = 2;
            c.txtLang.setText("C");
            FP.visited[2] = 2;
            count = count + 1;
        }
        if(chkBoxCPP.isSelected())
        {
            //FP.TabbedPanel.addTab("tabC++",c );
            FP.cal.put(3,c);
            FP.i[3] = 3;
            c.txtLang.setText("C++");
            FP.visited[3] = 3;
            count = count + 1;
        }
        if(chkBoxCS.isSelected())
        {
            //FP.TabbedPanel.addTab("tabC#",c );
            FP.cal.put(4,c);
            FP.i[4] = 4;
            c.txtLang.setText("C#");
            FP.visited[4] = 4;
            count = count + 1;
        }
        if(chkBoxCobol.isSelected())
        {
            //FP.TabbedPanel.addTab("tabCOBOL",c );
            FP.cal.put(5,c);
            FP.i[5] = 5;
            c.txtLang.setText("COBOL");
            FP.visited[5] = 5;
            count = count + 1;
        }
        if(chkBoxFortran.isSelected())
        {
            //FP.TabbedPanel.addTab("tabFortran",c );
            FP.cal.put(6,c);
            FP.i[6] = 6;
            c.txtLang.setText("Fortran");
            FP.visited[6] = 6;
            count = count + 1;
        }
        if(chkBoxHtml.isSelected())
        {
            //FP.TabbedPanel.addTab("tabHTML",c );
            FP.cal.put(7,c);
            FP.i[7] = 7;
            c.txtLang.setText("HTML");
            FP.visited[7] = 7;
            count = count + 1;
        }
        if(chkBoxJava.isSelected())
        {
            //FP.TabbedPanel.addTab("tabJava",c );
            FP.cal.put(8,c);
            FP.i[8] = 8;
            c.txtLang.setText("Java");
            FP.visited[8] = 8;
            count = count + 1;
        }
        if(chkBoxJavaScript.isSelected())
        {
            //FP.TabbedPanel.addTab("tabJavaScript",c );
            FP.cal.put(9,c);
            FP.i[9] = 9;
            c.txtLang.setText("Java Script");
            FP.visited[9] = 9;
            count = count + 1;
        }
        if(chkBoxVBScript.isSelected())
        {
            //FP.TabbedPanel.addTab("VBScript",c );
            FP.cal.put(10,c);
            FP.i[10] = 10;
            count = count + 1;
            c.txtLang.setText("VB Script");
            FP.visited[10] = 10;          
        }
        if(chkBoxVisualBasic.isSelected())
        {
            //FP.TabbedPanel.addTab("tabVisualBasic",c );
            FP.cal.put(11,c);
            FP.i[11] = 11;
            count = count + 1; 
            c.txtLang.setText("Visual Basic");
            FP.visited[11] = 11;
               
        }
        
        if (count > 1) {
            JOptionPane.showMessageDialog(null, "Select only one language");
        }
        else {
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnDoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeLanguage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeLanguage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeLanguage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeLanguage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeLanguage(new FP()).setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    public static javax.swing.JCheckBox chkBoxAda;
    public static javax.swing.JCheckBox chkBoxAssembler;
    public static javax.swing.JCheckBox chkBoxC;
    public static javax.swing.JCheckBox chkBoxCPP;
    public static javax.swing.JCheckBox chkBoxCS;
    public static javax.swing.JCheckBox chkBoxCobol;
    public static javax.swing.JCheckBox chkBoxFortran;
    private javax.swing.ButtonGroup chkBoxGrp;
    public static javax.swing.JCheckBox chkBoxHtml;
    public static javax.swing.JCheckBox chkBoxJava;
    public static javax.swing.JCheckBox chkBoxJavaScript;
    public static javax.swing.JCheckBox chkBoxVBScript;
    public static javax.swing.JCheckBox chkBoxVisualBasic;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
