/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cecs543;

import java.util.Map;

/**
 *
 * @author Ankush
 */
public class VAF extends javax.swing.JFrame {

    /**
     * Creates new form VAF
     */
     int q1;
     int q2;
     int q3;
     int q4;
     int q5;
     int q6;
     int q7;
     int q8;
     int q9;
     int q10;
     int q11;
     int q12;
     int q13;
     int q14;
    
     public FP fp;
    public VAF(FP fp) {
        initComponents();
        this.fp = fp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbBoxQ1 = new javax.swing.JComboBox<>();
        cmbBoxQ2 = new javax.swing.JComboBox<>();
        cmbBoxQ3 = new javax.swing.JComboBox<>();
        cmbBoxQ4 = new javax.swing.JComboBox<>();
        cmbBoxQ5 = new javax.swing.JComboBox<>();
        cmbBoxQ6 = new javax.swing.JComboBox<>();
        cmbBoxQ7 = new javax.swing.JComboBox<>();
        cmbBoxQ8 = new javax.swing.JComboBox<>();
        cmbBoxQ9 = new javax.swing.JComboBox<>();
        cmbBoxQ10 = new javax.swing.JComboBox<>();
        cmbBoxQ11 = new javax.swing.JComboBox<>();
        cmbBoxQ12 = new javax.swing.JComboBox<>();
        cmbBoxQ13 = new javax.swing.JComboBox<>();
        cmbBoxQ14 = new javax.swing.JComboBox<>();
        lblQ1 = new javax.swing.JLabel();
        lblQ2 = new javax.swing.JLabel();
        lblQ3 = new javax.swing.JLabel();
        lblQ4 = new javax.swing.JLabel();
        lblQ5 = new javax.swing.JLabel();
        lblQ6 = new javax.swing.JLabel();
        lblQ7 = new javax.swing.JLabel();
        lblQ8 = new javax.swing.JLabel();
        lblQ9 = new javax.swing.JLabel();
        lblQ10 = new javax.swing.JLabel();
        lblQ11 = new javax.swing.JLabel();
        lblQ12 = new javax.swing.JLabel();
        lblQ13 = new javax.swing.JLabel();
        lblQ14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnDone = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmbBoxQ1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        cmbBoxQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxQ1ActionPerformed(evt);
            }
        });

        cmbBoxQ2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        cmbBoxQ3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        cmbBoxQ4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        cmbBoxQ5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        cmbBoxQ6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        cmbBoxQ7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        cmbBoxQ8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        cmbBoxQ9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        cmbBoxQ10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        cmbBoxQ11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        cmbBoxQ12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        cmbBoxQ13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        cmbBoxQ14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        lblQ1.setText("Does the system require reliable backup and recovery? ");

        lblQ2.setText("Are specialized data communications required to transfer information to or from the application? ");

        lblQ3.setText("Are there distributed processing functions? ");

        lblQ4.setText("Is performance critical? ");

        lblQ5.setText("Will the system run in an existing, heavily utilized operational environment? ");

        lblQ6.setText("Does the system require on-line data entry? ");

        lblQ7.setText("Does the on-line data entry require the input transaction to be built over multiple screens or operations? ");

        lblQ8.setText("Are the internal logical files updated on-line? ");

        lblQ9.setText("Are the inputs, outputs, files, or inquiries complex? ");

        lblQ10.setText("Is the internal processing complex? ");

        lblQ11.setText("Is the code designed to be reusable? ");

        lblQ12.setText("Are conversion and installation included in the design? ");

        lblQ13.setText("Is the system designed for multiple installations in different organizations? ");

        lblQ14.setText("Is the application designed to facilitate change and for ease of use by the user? ");

        jLabel1.setText("Assign a value from 0 to 5 for each of the following Value Adjustment Factors:");

        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQ8)
                            .addComponent(lblQ9)
                            .addComponent(lblQ11)
                            .addComponent(lblQ10)
                            .addComponent(lblQ12)
                            .addComponent(lblQ13)
                            .addComponent(lblQ14))
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbBoxQ9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBoxQ8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBoxQ10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBoxQ11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBoxQ12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBoxQ13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBoxQ14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQ7)
                                    .addComponent(lblQ6)
                                    .addComponent(lblQ5)
                                    .addComponent(lblQ4)
                                    .addComponent(lblQ3)
                                    .addComponent(lblQ2)
                                    .addComponent(lblQ1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbBoxQ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBoxQ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBoxQ5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBoxQ6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBoxQ7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBoxQ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBoxQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnDone)
                        .addGap(37, 37, 37)
                        .addComponent(btnCancel)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addComponent(lblQ1)
                        .addGap(17, 17, 17)
                        .addComponent(lblQ2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmbBoxQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbBoxQ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQ3)
                    .addComponent(cmbBoxQ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQ4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbBoxQ4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQ5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbBoxQ5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxQ6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ7)
                    .addComponent(cmbBoxQ7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxQ8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ9)
                    .addComponent(cmbBoxQ9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ10)
                    .addComponent(cmbBoxQ10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxQ11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQ11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ12)
                    .addComponent(cmbBoxQ12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ13)
                    .addComponent(cmbBoxQ13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ14)
                    .addComponent(cmbBoxQ14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDone)
                    .addComponent(btnCancel))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        Integer sum = 0;
        //calculation c = new calculation();
        sum = sum + Integer.parseInt(cmbBoxQ1.getSelectedItem().toString());
        sum = sum + Integer.parseInt(cmbBoxQ2.getSelectedItem().toString());
        sum = sum + Integer.parseInt(cmbBoxQ3.getSelectedItem().toString());
        sum = sum + Integer.parseInt(cmbBoxQ4.getSelectedItem().toString());
        sum = sum + Integer.parseInt(cmbBoxQ5.getSelectedItem().toString());
        sum = sum + Integer.parseInt(cmbBoxQ6.getSelectedItem().toString());
        sum = sum + Integer.parseInt(cmbBoxQ7.getSelectedItem().toString());
        sum = sum + Integer.parseInt(cmbBoxQ8.getSelectedItem().toString());
        sum = sum + Integer.parseInt(cmbBoxQ9.getSelectedItem().toString());
        sum = sum + Integer.parseInt(cmbBoxQ10.getSelectedItem().toString());
        sum = sum + Integer.parseInt(cmbBoxQ11.getSelectedItem().toString());
        sum = sum + Integer.parseInt(cmbBoxQ12.getSelectedItem().toString());
        sum = sum + Integer.parseInt(cmbBoxQ13.getSelectedItem().toString());
        sum = sum + Integer.parseInt(cmbBoxQ14.getSelectedItem().toString());
        
        try {
            int selectedIndex = fp.TabbedPanel.getSelectedIndex();
            calculation c = (calculation) fp.TabbedPanel.getComponentAt(selectedIndex);
            c.txtVA.setText(sum.toString());
            //System.out.println(selectedIndex);
            String LangName = c.getLanguage();
            //System.out.println("Lang Name:" + LangName);        
            if (LangName.equals("Assembler")){
                FP.cal.get(FP.i[0]).txtVA.setText(sum.toString());
            }
                        
            if (LangName.equals("Ada")){
                FP.cal.get(FP.i[1]).txtVA.setText(sum.toString());
            }
            if (LangName.equals("C")){
                FP.cal.get(FP.i[2]).txtVA.setText(sum.toString());  
            }
            if (LangName.equals("C++")){
                FP.cal.get(FP.i[3]).txtVA.setText(sum.toString());
            }
            if (LangName.equals("C#")){ 
                FP.cal.get(FP.i[4]).txtVA.setText(sum.toString());
            }
            if (LangName.equals("COBOL")){
                FP.cal.get(FP.i[5]).txtVA.setText(sum.toString());
            }
            if (LangName.equals("Fortran")){
                FP.cal.get(FP.i[6]).txtVA.setText(sum.toString());
            }
            if (LangName.equals("HTML")){
                FP.cal.get(FP.i[7]).txtVA.setText(sum.toString());
            }
            if (LangName.equals("Java")){
                //System.out.println("Java IF Running");
                FP.cal.get(FP.i[8]).txtVA.setText(sum.toString());
            }
            if (LangName.equals("Java Script")){
                FP.cal.get(FP.i[9]).txtVA.setText(sum.toString());
            }
            if (LangName.equals("VB Script")){
                FP.cal.get(FP.i[10]).txtVA.setText(sum.toString());
            }
            if (LangName.equals("Visual Basic")){
                FP.cal.get(FP.i[11]).txtVA.setText(sum.toString());
            }
            
//        int selectedIndexTab = FP.TabbedPanel.getSelectedIndex();
//        System.out.println(selectedIndex);
//        calculation c = (calculation) FP.TabbedPanel.getComponentAt(selectedIndex);
            c.q1 = cmbBoxQ1.getSelectedIndex();
            c.q2 = cmbBoxQ2.getSelectedIndex();
            c.q3 = cmbBoxQ3.getSelectedIndex();
            c.q4 = cmbBoxQ4.getSelectedIndex();
            c.q5 = cmbBoxQ5.getSelectedIndex();
            c.q6 = cmbBoxQ6.getSelectedIndex();
            c.q7 = cmbBoxQ7.getSelectedIndex();
            c.q8 = cmbBoxQ8.getSelectedIndex();
            c.q9 = cmbBoxQ9.getSelectedIndex();
            c.q10 = cmbBoxQ10.getSelectedIndex();
            c.q11 = cmbBoxQ11.getSelectedIndex();
            c.q12 = cmbBoxQ12.getSelectedIndex();
            c.q13 = cmbBoxQ13.getSelectedIndex();
            c.q14 = cmbBoxQ14.getSelectedIndex();
        }
        catch(Exception ex){
        
        }
        
        this.setVisible(false);
        
    }//GEN-LAST:event_btnDoneActionPerformed

    private void cmbBoxQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxQ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBoxQ1ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAF(new FP()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    javax.swing.JButton btnDone;
    public javax.swing.JComboBox<String> cmbBoxQ1;
    public javax.swing.JComboBox<String> cmbBoxQ10;
    public javax.swing.JComboBox<String> cmbBoxQ11;
    public javax.swing.JComboBox<String> cmbBoxQ12;
    public javax.swing.JComboBox<String> cmbBoxQ13;
    public javax.swing.JComboBox<String> cmbBoxQ14;
    public javax.swing.JComboBox<String> cmbBoxQ2;
    public javax.swing.JComboBox<String> cmbBoxQ3;
    public javax.swing.JComboBox<String> cmbBoxQ4;
    public javax.swing.JComboBox<String> cmbBoxQ5;
    public javax.swing.JComboBox<String> cmbBoxQ6;
    public javax.swing.JComboBox<String> cmbBoxQ7;
    public javax.swing.JComboBox<String> cmbBoxQ8;
    public javax.swing.JComboBox<String> cmbBoxQ9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblQ1;
    private javax.swing.JLabel lblQ10;
    private javax.swing.JLabel lblQ11;
    private javax.swing.JLabel lblQ12;
    private javax.swing.JLabel lblQ13;
    private javax.swing.JLabel lblQ14;
    private javax.swing.JLabel lblQ2;
    private javax.swing.JLabel lblQ3;
    private javax.swing.JLabel lblQ4;
    private javax.swing.JLabel lblQ5;
    private javax.swing.JLabel lblQ6;
    private javax.swing.JLabel lblQ7;
    private javax.swing.JLabel lblQ8;
    private javax.swing.JLabel lblQ9;
    // End of variables declaration//GEN-END:variables
}
